[#ZLlm1pbe] Support multiple versions of the helm client
Package all versions needed by vagrant, our CI, an CaaSP3.
Detect and choose version to use at runtime (brain tests).

diff --git a/src/scf-release/jobs/acceptance-tests-brain/templates/run.erb b/src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
--- a/src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
+++ b/src/scf-release/jobs/acceptance-tests-brain/templates/run.erb
@@ -2,11 +2,31 @@
 
 set -o errexit
 
+# Use the primary linked helm client to determine the actual version
+# of the server. Check if we have a client for that version packaged,
+# and if yes, put it on the PATH. Else fails with a nice message.
+
+HBASE=/var/vcap/packages/helm/bin
+HELM_VERSION="$(${HBASE}/helm version| grep Server | sed -e 's/.*"v//' -e 's/".*//')"
+
+echo Packaged helm clients ...
+( cd ${HBASE} ; find . -type f | sed -e 's/^/= /' )
+echo Helm server ${HELM_VERSION}
+echo Compare
+
+if test -f "${HBASE}/${HELM_VERSION}/helm"
+then
+    echo Match
+else
+    echo "Helm server ${HELM_VERSION} not supported, only: $(cd ${HBASE} ; ls | sort)"
+    exit 1
+fi
+
+export PATH="${HBASE}/${HELM_VERSION}:${PATH}"
 export PATH="/var/vcap/packages/cli/bin:${PATH}"
 export PATH="/var/vcap/packages/kubectl/bin:${PATH}"
 export PATH="/var/vcap/packages/credhub-cli/bin:${PATH}"
 export PATH="/var/vcap/packages/mariadb-client/bin:${PATH}"
-export PATH="/var/vcap/packages/helm/bin:${PATH}"
 export PATH="/var/vcap/packages/acceptance-tests-brain/bin:${PATH}"
 
 source /var/vcap/jobs/acceptance-tests-brain/bin/environment.sh
@@ -18,8 +38,9 @@ export SCRIPTS_FOLDER="${BRAIN}/test-scripts"
 # Announce the versions of the helper apps used by this job. This also
 # causes an early abort if these are somehow missing, or not
 # accessible/found through the PATH.
-cf version
-kubectl version
+cf version      | sed -e 's/^/CF   = /'
+kubectl version | sed -e 's/^/KUBE = /'
+helm version    | sed -e 's/^/HELM = /'
 
 shopt -s nullglob
 for i in "${ASSETS}/plugins/"*; do
