HCF-732 Add cf-uaac as a package in src/hcf-release, remove jq
It turns out that uaac is better for our puposes. And we can just have
a Gemfile that depends on it for packaging.

diff --git a/src/hcf-release/packages/ruby-2.3/packaging b/src/hcf-release/packages/ruby-2.3/packaging
--- a/src/hcf-release/packages/ruby-2.3/packaging
+++ b/src/hcf-release/packages/ruby-2.3/packaging
@@ -3,6 +3,8 @@ set -e
 
 # We grab the latest versions that are in the directory
 RUBY_VERSION=`ls -r ruby-2.3/ruby-* | sed 's/ruby-2.3\/ruby-\(.*\)\.tar\.gz/\1/' | head -1`
+RUBYGEMS_VERSION=`ls -r ruby-2.3/rubygems-* | sed 's/ruby-2.3\/rubygems-\(.*\)\.tgz/\1/' | head -1`
+BUNDLER_VERSION=`ls -r ruby-2.3/bundler-* | sed 's/ruby-2.3\/bundler-\(.*\)\.gem/\1/' | head -1`
 
 tar xzf ruby-2.3/ruby-${RUBY_VERSION}.tar.gz
 (
@@ -12,3 +14,18 @@ tar xzf ruby-2.3/ruby-${RUBY_VERSION}.tar.gz
   make
   make install
 )
+
+tar zxvf ruby-2.3/rubygems-${RUBYGEMS_VERSION}.tgz
+(
+  set -e
+  cd rubygems-${RUBYGEMS_VERSION}
+
+  ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb
+
+  if [[ $? != 0 ]] ; then
+    echo "Cannot install rubygems"
+    exit 1
+  fi
+)
+
+${BOSH_INSTALL_TARGET}/bin/gem install ruby-2.3/bundler-${BUNDLER_VERSION}.gem --local --no-ri --no-rdoc
