[HCF-982] Added more sanity checks.

diff --git a/src/hcf-release/jobs/acceptance-tests-autoscaler/templates/run.erb b/src/hcf-release/jobs/acceptance-tests-autoscaler/templates/run.erb
--- a/src/hcf-release/jobs/acceptance-tests-autoscaler/templates/run.erb
+++ b/src/hcf-release/jobs/acceptance-tests-autoscaler/templates/run.erb
@@ -1,13 +1,20 @@
 #!/bin/bash
 set -e
 
+<% if properties.uaa.scim.users.empty? %>
+     echo "Aborting. No admin user configured."
+     exit 1
+<% end %>
+<% if properties.uaa.scim.users.length > 1 %>
+     echo "Aborting. Configured more than one admin user: (<%= userinfo %>)"
+     exit 1
+<% end %>
+
 <% userinfo = properties.uaa.scim.users.first
    if !userinfo.include? 'cloud_controller.admin'
 %>
-
-     echo "Configured admin user is not cloud_controller.admin (<%= userinfo %>)"
+     echo "Aborting. Configured admin user is not cloud_controller.admin (<%= userinfo %>)"
      exit 1
-
 <% end
 
    username = userinfo.split('|').first
diff --git a/src/hcf-release/jobs/uaa-create-user/templates/run.erb b/src/hcf-release/jobs/uaa-create-user/templates/run.erb
--- a/src/hcf-release/jobs/uaa-create-user/templates/run.erb
+++ b/src/hcf-release/jobs/uaa-create-user/templates/run.erb
@@ -8,6 +8,15 @@
 
 set -o errexit -o nounset
 
+<% if properties.uaa.scim.users.empty? %>
+     echo "Aborting. No admin user configured."
+     exit 1
+<% end %>
+<% if properties.uaa.scim.users.length > 1 %>
+     echo "Aborting. Configured more than one admin user: (<%= userinfo %>)"
+     exit 1
+<% end %>
+
 # Report progress to the user; use as printf
 status() {
     local fmt="${1}"
